### ISSUE TITLE
vsac apis are no longer working

### ISSUE THREAD

**Issue by tusharkantawp** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#89] opened 2023-01-12 15:21 UTC
On the authoring tool none of the vsac execution works even after correct authentication. I am seeing this issue since yesterday. After searching for any keyword it just blanks out after sometime. If I do a network inspect using inspect tool, it just says 404 error. Same during any value set code or system validations. we need an urgent fix

**Comment by cmoesel** [comment] 2023-01-12 15:42
Hello @tusharkantawp. Thank you for reporting this. It looks like VSAC removed their `https://cts.nlm.nih.gov/fhir/r4` endpoint. This is the endpoint that the CDS Authoring Tool uses by default.

It looks like we should now be using `https://cts.nlm.nih.gov/fhir` (without the `r4`) instead.

If you a running your own instance of the CDS Authoring Tool, you can change the default VSAC endpoint in the `api/config.js` file -- or you can set it via the `TERMINOLOGY_ENDPOINT` environment variable.

If you are using the publicly hosted version of the CDS Authoring Tool, you'll have to wait for us to implement the fix on our public deployment. I expect we should be able to do this today.

**Comment by tusharkantawp** [comment] 2023-01-12 15:46
Thanks for quick response. I will try it out and update. This is very serious as lot of old projects are deployed. We have to check everything now.

**Comment by cmoesel** [comment] 2023-01-12 16:00
If you update the `api/config.js` file w/ the new endpoint, you will also need to update some tests for them to continue passing.  You can see what needs to be updated here: https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool/compare/master...vsac-endpoint

**Comment by tusharkantawp** [comment] 2023-01-12 16:04
ok thank you. I just updated config.js file but result is same. I will update all files as you have mentioned and rerun.

**Comment by tusharkantawp** [comment] 2023-01-12 16:26
finally worked thanks

**Comment by cmoesel** [comment] 2023-01-12 16:33
Sorry, I was in a meeting. But yes, I tested this and confirmed it worked before sending you the link to the commit.

**Comment by cmoesel** [comment] 2023-01-12 21:30
This was also resolved in production this afternoon, so I am closing this issue.

**Closed by cmoesel** 2023-01-12 21:30 UTC
